In [27]:
# Homework 3 _ Feature Group

In [3]:
#%pip install --force-reinstall 'sagemaker>=2.200,<3'

Collecting sagemaker<3,>=2.200
  Downloading sagemaker-2.257.3-py3-none-any.whl.metadata (17 kB)

Collecting attrs<26,>=24 (from sagemaker<3,>=2.200)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)

Collecting boto3<2.0,>=1.42.2 (from sagemaker<3,>=2.200)
  Using cached boto3-1.43.14-py3-none-any.whl.metadata (6.6 kB)

Collecting cloudpickle>=2.2.1 (from sagemaker<3,>=2.200)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting docker (from sagemaker<3,>=2.200)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)

Collecting fastapi (from sagemaker<3,>=2.200)
  Using cached fastapi-0.136.3-py3-none-any.whl.metadata (27 kB)

Collecting google-pasta (from sagemaker<3,>=2.200)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting graphene<4,>=3 (from sagemaker<3,>=2.200)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)

Collecting importlib-metadata<7.0,>=1.4.0 (from sagemaker<3,>=2.200)
  Using cached importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)
Collecting jsonschema (from sagemaker<3,>=2.200)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)

Collecting numpy<3.0,>=1.26.4 (from sagemaker<3,>=2.200)
  Using cached numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)

Collecting omegaconf<3,>=2.2 (from sagemaker<3,>=2.200)
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting packaging<25,>=23.0 (from sagemaker<3,>=2.200)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)

Collecting pandas>=2.3.0 (from sagemaker<3,>=2.200)
  Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)

Collecting pathos (from sagemaker<3,>=2.200)
  Downloading pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs (from sagemaker<3,>=2.200)
  Using cached platformdirs-4.9.6-py3-none-any.whl.metadata (4.7 kB)

Collecting protobuf<7.0,>=3.12 (from sagemaker<3,>=2.200)
  Using cached protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)

Collecting psutil (from sagemaker<3,>=2.200)
  Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)

Collecting pyyaml>=6.0.1 (from sagemaker<3,>=2.200)
  Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests (from sagemaker<3,>=2.200)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)

Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3,>=2.200)
  Downloading sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Collecting schema (from sagemaker<3,>=2.200)
  Using cached schema-0.7.8-py2.py3-none-any.whl.metadata (34 kB)

Collecting smdebug-rulesconfig==1.0.1 (from sagemaker<3,>=2.200)
  Using cached smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl.metadata (943 bytes)
Collecting tblib<4,>=1.7.0 (from sagemaker<3,>=2.200)
  Using cached tblib-3.2.2-py3-none-any.whl.metadata (27 kB)

Collecting tqdm (from sagemaker<3,>=2.200)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting urllib3<3.0.0,>=1.26.8 (from sagemaker<3,>=2.200)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)

Collecting uvicorn (from sagemaker<3,>=2.200)
  Using cached uvicorn-0.48.0-py3-none-any.whl.metadata (6.7 kB)

Collecting botocore<1.44.0,>=1.43.14 (from boto3<2.0,>=1.42.2->sagemaker<3,>=2.200)
  Using cached botocore-1.43.14-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0,>=1.42.2->sagemaker<3,>=2.200)

  Using cached jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.18.0,>=0.17.0 (from boto3<2.0,>=1.42.2->sagemaker<3,>=2.200)
  Using cached s3transfer-0.17.0-py3-none-any.whl.metadata (1.7 kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.44.0,>=1.43.14->boto3<2.0,>=1.42.2->sagemaker<3,>=2.200)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)

Collecting graphql-core<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3,>=2.200)
  Using cached graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3,>=2.200)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Collecting typing-extensions<5,>=4.7.1 (from graphene<4,>=3->sagemaker<3,>=2.200)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)

Collecting zipp>=0.5 (from importlib-metadata<7.0,>=1.4.0->sagemaker<3,>=2.200)
  Using cached zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<3,>=2.2->sagemaker<3,>=2.200)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl

Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.14->boto3<2.0,>=1.42.2->sagemaker<3,>=2.200)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)

Collecting pydantic<3.0.0,>=2.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting rich<15.0.0,>=13.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)

  Using cached rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Collecting mock<5.0,>4.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached mock-4.0.3-py3-none-any.whl.metadata (2.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->sagemaker<3,>=2.200)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)

Collecting referencing>=0.28.4 (from jsonschema->sagemaker<3,>=2.200)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)

Collecting rpds-py>=0.25.0 (from jsonschema->sagemaker<3,>=2.200)
  Using cached rpds_py-0.30.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)

Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)

  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2.200)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)

Collecting charset_normalizer<4,>=2 (from requests->sagemaker<3,>=2.200)
  Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests->sagemaker<3,>=2.200)
  Using cached idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2023.5.7 (from requests->sagemaker<3,>=2.200)
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)

Collecting starlette>=0.46.0 (from fastapi->sagemaker<3,>=2.200)
  Downloading starlette-1.1.0-py3-none-any.whl.metadata (6.3 kB)
Collecting annotated-doc>=0.0.2 (from fastapi->sagemaker<3,>=2.200)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)

Collecting anyio<5,>=3.6.2 (from starlette>=0.46.0->fastapi->sagemaker<3,>=2.200)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3,>=2.200)
  Downloading ppft-1.7.8-py3-none-any.whl.metadata (12 kB)

Collecting dill>=0.4.1 (from pathos->sagemaker<3,>=2.200)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pox>=0.3.7 (from pathos->sagemaker<3,>=2.200)
  Downloading pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)

Collecting multiprocess>=0.70.19 (from pathos->sagemaker<3,>=2.200)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting click>=7.0 (from uvicorn->sagemaker<3,>=2.200)
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)

Collecting h11>=0.8 (from uvicorn->sagemaker<3,>=2.200)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading sagemaker-2.257.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 106.3 MB/s  0:00:00
Using cached smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl (20 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)

Using cached boto3-1.43.14-py3-none-any.whl (140 kB)
Using cached botocore-1.43.14-py3-none-any.whl (15.1 MB)

Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_core-3.2.8-py3-none-any.whl (207 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached importlib_metadata-6.11.0-py3-none-any.whl (23 kB)
Using cached jmespath-1.1.0-py3-none-any.whl (20 kB)
Using cached numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)

Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Using cached protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached s3transfer-0.17.0-py3-none-any.whl (86 kB)

Downloading sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Using cached platformdirs-4.9.6-py3-none-any.whl (21 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
Using cached rich-14.3.4-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)

Using cached tblib-3.2.2-py3-none-any.whl (12 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/10.9 MB ? eta -:--:--

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 133.1 MB/s  0:00:00
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-0.30.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (394 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached zipp-4.1.0-py3-none-any.whl (10 kB)
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (216 kB)
Using cached idna-3.16-py3-none-any.whl (74 kB)
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached fastapi-0.136.3-py3-none-any.whl (117 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading starlette-1.1.0-py3-none-any.whl (72 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)

Downloading pathos-0.3.5-py3-none-any.whl (82 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading pox-0.3.7-py3-none-any.whl (29 kB)
Downloading ppft-1.7.8-py3-none-any.whl (56 kB)
Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Using cached schema-0.7.8-py2.py3-none-any.whl (19 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached uvicorn-0.48.0-py3-none-any.whl (71 kB)
Using cached click-8.4.1-py3-none-any.whl (116 kB)

Using cached h11-0.16.0-py3-none-any.whl (37 kB)

Installing collected packages: schema, antlr4-python3-runtime, zipp, urllib3, typing-extensions, tqdm, tblib, smdebug-rulesconfig, six, rpds-py, pyyaml, pygments, psutil, protobuf, ppft, pox, platformdirs, packaging, numpy, mock, mdurl, jmespath, idna, h11, graphql-core, dill, cloudpickle, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, uvicorn, typing-inspection, requests, referencing, python-dateutil, pydantic-core, omegaconf, multiprocess, markdown-it-py, importlib-metadata, graphql-relay, google-pasta, anyio, starlette, rich, pydantic, pathos, pandas, jsonschema-specifications, graphene, docker, botocore, s3transfer, jsonschema, fastapi, boto3, sagemaker-core, sagemaker
  Attempting uninstall: schema

    Found existing installation: schema 0.7.8
    Uninstalling schema-0.7.8:
      Successfully uninstalled schema-0.7.8
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9.3
    Uninstalling antlr4-python3-runtime-4.9.3:

      Successfully uninstalled antlr4-python3-runtime-4.9.3

  Attempting uninstall: zipp
    Found existing installation: zipp 4.1.0
    Uninstalling zipp-4.1.0:
      Successfully uninstalled zipp-4.1.0
  Attempting uninstall: urllib3
   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/61 [zipp]

    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/61 [zipp]

  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

      Successfully uninstalled typing_extensions-4.15.0
   ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]

  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]

    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]

  Attempting uninstall: tblib
    Found existing installation: tblib 3.2.2
    Uninstalling tblib-3.2.2:
      Successfully uninstalled tblib-3.2.2
  Attempting uninstall: smdebug-rulesconfig
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]

    Found existing installation: smdebug-rulesconfig 1.0.1
    Uninstalling smdebug-rulesconfig-1.0.1:
      Successfully uninstalled smdebug-rulesconfig-1.0.1
  Attempting uninstall: six
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]

    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

      Successfully uninstalled six-1.17.0
  Attempting uninstall: rpds-py
   ━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]

    Found existing installation: rpds-py 0.30.0
    Uninstalling rpds-py-0.30.0:
      Successfully uninstalled rpds-py-0.30.0
  Attempting uninstall: pyyaml
   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/61 [rpds-py]

    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/61 [rpds-py]

  Attempting uninstall: pygments
    Found existing installation: Pygments 2.20.0
   ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/61 [rpds-py]

    Uninstalling Pygments-2.20.0:
      Successfully uninstalled Pygments-2.20.0
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

  Attempting uninstall: psutil
    Found existing installation: psutil 7.2.2
    Uninstalling psutil-7.2.2:
      Successfully uninstalled psutil-7.2.2
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

  Attempting uninstall: protobuf
   ━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]

    Found existing installation: protobuf 6.33.6
    Uninstalling protobuf-6.33.6:
      Successfully uninstalled protobuf-6.33.6
   ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]

   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/61 [ppft]

  Attempting uninstall: platformdirs
    Found existing installation: platformdirs 4.9.6
   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/61 [ppft]

    Uninstalling platformdirs-4.9.6:
      Successfully uninstalled platformdirs-4.9.6
  Attempting uninstall: packaging
   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/61 [ppft]

    Found existing installation: packaging 26.2
    Uninstalling packaging-26.2:
      Successfully uninstalled packaging-26.2
   ━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/61 [ppft]

  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

  Attempting uninstall: mock
    Found existing installation: mock 4.0.3
    Uninstalling mock-4.0.3:
      Successfully uninstalled mock-4.0.3
   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

  Attempting uninstall: mdurl
    Found existing installation: mdurl 0.1.2
    Uninstalling mdurl-0.1.2:
      Successfully uninstalled mdurl-0.1.2
  Attempting uninstall: jmespath
    Found existing installation: jmespath 1.1.0
   ━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

    Uninstalling jmespath-1.1.0:
      Successfully uninstalled jmespath-1.1.0
  Attempting uninstall: idna
   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 21/61 [jmespath]

    Found existing installation: idna 3.16
    Uninstalling idna-3.16:
      Successfully uninstalled idna-3.16
   ━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━ 21/61 [jmespath]

  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: graphql-core
   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 24/61 [graphql-core]

    Found existing installation: graphql-core 3.2.8
    Uninstalling graphql-core-3.2.8:
      Successfully uninstalled graphql-core-3.2.8
   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 24/61 [graphql-core]

   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 24/61 [graphql-core]

  Attempting uninstall: dill
    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1
   ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 24/61 [graphql-core]

  Attempting uninstall: cloudpickle
    Found existing installation: cloudpickle 3.1.2
    Uninstalling cloudpickle-3.1.2:
      Successfully uninstalled cloudpickle-3.1.2
   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 25/61 [dill]

  Attempting uninstall: click
    Found existing installation: click 8.4.1
    Uninstalling click-8.4.1:
      Successfully uninstalled click-8.4.1
   ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 25/61 [dill]

  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.4.7
    Uninstalling charset-normalizer-3.4.7:
   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

      Successfully uninstalled charset-normalizer-3.4.7
   ━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━ 28/61 [charset_normalizer]

  Attempting uninstall: certifi
    Found existing installation: certifi 2026.5.20
    Uninstalling certifi-2026.5.20:
      Successfully uninstalled certifi-2026.5.20
  Attempting uninstall: attrs
   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 29/61 [certifi]

    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 29/61 [certifi]

  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.7.0
    Uninstalling annotated-types-0.7.0:
      Successfully uninstalled annotated-types-0.7.0
  Attempting uninstall: annotated-doc
   ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━ 29/61 [certifi]

    Found existing installation: annotated-doc 0.0.4
    Uninstalling annotated-doc-0.0.4:
      Successfully uninstalled annotated-doc-0.0.4
  Attempting uninstall: uvicorn
    Found existing installation: uvicorn 0.48.0
   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 32/61 [annotated-doc]

    Uninstalling uvicorn-0.48.0:
      Successfully uninstalled uvicorn-0.48.0
   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 32/61 [annotated-doc]

  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.2
    Uninstalling typing-inspection-0.4.2:
   ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━ 32/61 [annotated-doc]

      Successfully uninstalled typing-inspection-0.4.2
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 35/61 [requests]

  Attempting uninstall: referencing
   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 35/61 [requests]

    Found existing installation: referencing 0.37.0
    Uninstalling referencing-0.37.0:
      Successfully uninstalled referencing-0.37.0
   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 35/61 [requests]

  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
   ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━ 35/61 [requests]

  Attempting uninstall: pydantic-core
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 37/61 [python-dateutil]

    Found existing installation: pydantic_core 2.46.4
    Uninstalling pydantic_core-2.46.4:
      Successfully uninstalled pydantic_core-2.46.4
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 37/61 [python-dateutil]

  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.3.0
    Uninstalling omegaconf-2.3.0:
      Successfully uninstalled omegaconf-2.3.0
   ━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 37/61 [python-dateutil]

   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 39/61 [omegaconf]

  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.19
    Uninstalling multiprocess-0.70.19:
      Successfully uninstalled multiprocess-0.70.19
   ━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━ 39/61 [omegaconf]

  Attempting uninstall: markdown-it-py
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 40/61 [multiprocess]

    Found existing installation: markdown-it-py 4.2.0
    Uninstalling markdown-it-py-4.2.0:
      Successfully uninstalled markdown-it-py-4.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 40/61 [multiprocess]

  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 6.11.0
    Uninstalling importlib-metadata-6.11.0:
      Successfully uninstalled importlib-metadata-6.11.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 42/61 [importlib-metadata]

  Attempting uninstall: graphql-relay
    Found existing installation: graphql-relay 3.2.0
    Uninstalling graphql-relay-3.2.0:
      Successfully uninstalled graphql-relay-3.2.0
  Attempting uninstall: google-pasta
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 42/61 [importlib-metadata]

    Found existing installation: google-pasta 0.2.0
    Uninstalling google-pasta-0.2.0:
      Successfully uninstalled google-pasta-0.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━ 42/61 [importlib-metadata]

  Attempting uninstall: anyio
    Found existing installation: anyio 4.13.0
    Uninstalling anyio-4.13.0:
      Successfully uninstalled anyio-4.13.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 45/61 [anyio]

  Attempting uninstall: starlette
    Found existing installation: starlette 0.52.1
    Uninstalling starlette-0.52.1:
      Successfully uninstalled starlette-0.52.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━ 45/61 [anyio]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 46/61 [starlette]

  Attempting uninstall: rich
    Found existing installation: rich 14.3.4
    Uninstalling rich-14.3.4:
      Successfully uninstalled rich-14.3.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━ 46/61 [starlette]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 47/61 [rich]

  Attempting uninstall: pydantic
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 47/61 [rich]

    Found existing installation: pydantic 2.13.4
    Uninstalling pydantic-2.13.4:
      Successfully uninstalled pydantic-2.13.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 48/61 [pydantic]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━ 48/61 [pydantic]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 49/61 [pathos]

  Attempting uninstall: pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 49/61 [pathos]

    Found existing installation: pandas 2.3.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━ 49/61 [pathos]

    Uninstalling pandas-2.3.3:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

      Successfully uninstalled pandas-2.3.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

  Attempting uninstall: jsonschema-specifications
    Found existing installation: jsonschema-specifications 2025.9.1
    Uninstalling jsonschema-specifications-2025.9.1:
      Successfully uninstalled jsonschema-specifications-2025.9.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━ 50/61 [pandas]

  Attempting uninstall: graphene
    Found existing installation: graphene 3.4.3
    Uninstalling graphene-3.4.3:
      Successfully uninstalled graphene-3.4.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━ 52/61 [graphene]

  Attempting uninstall: docker
    Found existing installation: docker 7.1.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 53/61 [docker]

    Uninstalling docker-7.1.0:
      Successfully uninstalled docker-7.1.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 53/61 [docker]

  Attempting uninstall: botocore
    Found existing installation: botocore 1.43.14
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━ 53/61 [docker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

    Uninstalling botocore-1.43.14:
      Successfully uninstalled botocore-1.43.14
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

  Attempting uninstall: s3transfer
    Found existing installation: s3transfer 0.17.0
    Uninstalling s3transfer-0.17.0:
      Successfully uninstalled s3transfer-0.17.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 54/61 [botocore]

  Attempting uninstall: jsonschema
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 55/61 [s3transfer]

    Found existing installation: jsonschema 4.26.0
    Uninstalling jsonschema-4.26.0:
      Successfully uninstalled jsonschema-4.26.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 55/61 [s3transfer]

  Attempting uninstall: fastapi
    Found existing installation: fastapi 0.136.3
    Uninstalling fastapi-0.136.3:
      Successfully uninstalled fastapi-0.136.3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 57/61 [fastapi]

  Attempting uninstall: boto3
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 57/61 [fastapi]

    Found existing installation: boto3 1.43.14
    Uninstalling boto3-1.43.14:
      Successfully uninstalled boto3-1.43.14
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 58/61 [boto3]

  Attempting uninstall: sagemaker-core
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 58/61 [boto3]

    Found existing installation: sagemaker-core 2.12.0
    Uninstalling sagemaker-core-2.12.0:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 58/61 [boto3]

      Successfully uninstalled sagemaker-core-2.12.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━ 58/61 [boto3]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 59/61 [sagemaker-core]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 59/61 [sagemaker-core]

  Attempting uninstall: sagemaker
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 59/61 [sagemaker-core]

    Found existing installation: sagemaker 3.12.0
    Uninstalling sagemaker-3.12.0:
      Successfully uninstalled sagemaker-3.12.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 60/61 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 60/61 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 60/61 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 60/61 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 60/61 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺ 60/61 [sagemaker]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61/61 [sagemaker]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autogluon-multimodal 1.5.0 requires nvidia-ml-py3<8.0,>=7.352.0, which is not installed.
autogluon-timeseries 1.5.0 requires chronos-forecasting<2.4,>=2.2.2, which is not installed.
autogluon-timeseries 1.5.0 requires einops<1,>=0.7, which is not installed.
autogluon-timeseries 1.5.0 requires peft<0.18,>=0.13.0, which is not installed.
dash 2.18.1 requires dash-core-components==2.0.0, which is not installed.
dash 2.18.1 requires dash-html-components==2.0.0, which is not installed.
dash 2.18.1 requires dash-table==5.0.0, which is not installed.
aiobotocore 3.6.0 requires botocore<1.43.1,>=1.42.90, but you have botocore 1.43.14 which is incompatible.
amazon-sagemaker-sql-editor 0.2.4 requires rpds-py==0.27.1, but you have rpds-py 0.30.0 which is incompatible.
amazon-sagemaker-sql-magic 0.1.4 requires numpy<2, but you have numpy 2.4.6 which is incompatible.
amazon-sagemaker-sql-magic 0.1.4 requires sqlparse==0.5.0, but you have sqlparse 0.5.5 which is incompatible.
autogluon-common 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.4.6 which is incompatible.
autogluon-common 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.3 which is incompatible.
autogluon-common 1.5.0 requires psutil<7.2.0,>=5.7.3, but you have psutil 7.2.2 which is incompatible.
autogluon-common 1.5.0 requires pyarrow<21.0.0,>=7.0.0, but you have pyarrow 23.0.1 which is incompatible.
autogluon-core 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.4.6 which is incompatible.
autogluon-core 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.3 which is incompatible.
autogluon-core 1.5.0 requires scikit-learn<1.8.0,>=1.4.0, but you have scikit-learn 1.8.0 which is incompatible.
autogluon-core 1.5.0 requires scipy<1.17,>=1.5.4, but you have scipy 1.17.1 which is incompatible.
autogluon-features 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.4.6 which is incompatible.
autogluon-features 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.3 which is incompatible.
autogluon-features 1.5.0 requires scikit-learn<1.8.0,>=1.4.0, but you have scikit-learn 1.8.0 which is incompatible.
autogluon-multimodal 1.5.0 requires fsspec[http]<=2025.3, but you have fsspec 2026.4.0 which is incompatible.
autogluon-multimodal 1.5.0 requires jsonschema<4.24,>=4.18, but you have jsonschema 4.26.0 which is incompatible.
autogluon-multimodal 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.4.6 which is incompatible.
autogluon-multimodal 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.3 which is incompatible.
autogluon-multimodal 1.5.0 requires Pillow<12,>=10.0.1, but you have pillow 12.2.0 which is incompatible.
autogluon-multimodal 1.5.0 requires scikit-learn<1.8.0,>=1.4.0, but you have scikit-learn 1.8.0 which is incompatible.
autogluon-multimodal 1.5.0 requires scipy<1.17,>=1.5.4, but you have scipy 1.17.1 which is incompatible.
autogluon-multimodal 1.5.0 requires torch<2.10,>=2.6, but you have torch 2.12.0 which is incompatible.
autogluon-tabular 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.4.6 which is incompatible.
autogluon-tabular 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.3 which is incompatible.
autogluon-tabular 1.5.0 requires scikit-learn<1.8.0,>=1.4.0, but you have scikit-learn 1.8.0 which is incompatible.
autogluon-tabular 1.5.0 requires scipy<1.17,>=1.5.4, but you have scipy 1.17.1 which is incompatible.
autogluon-timeseries 1.5.0 requires numpy<2.4.0,>=1.25.0, but you have numpy 2.4.6 which is incompatible.
autogluon-timeseries 1.5.0 requires pandas<2.4.0,>=2.0.0, but you have pandas 3.0.3 which is incompatible.
autogluon-timeseries 1.5.0 requires scipy<1.17,>=1.5.4, but you have scipy 1.17.1 which is incompatible.
autogluon-timeseries 1.5.0 requires torch<2.10,>=2.6, but you have torch 2.12.0 which is incompatible.
autovizwidget 0.23.0 requires pandas<3.0.0, but you have pandas 3.0.3 which is incompatible.
catboost 1.2.7 requires numpy<2.0,>=1.16.0, but you have numpy 2.4.6 which is incompatible.
dash 2.18.1 requires Flask<3.1,>=1.0.4, but you have flask 3.1.3 which is incompatible.
dash 2.18.1 requires Werkzeug<3.1, but you have werkzeug 3.1.8 which is incompatible.
fugue 0.9.7 requires pandas<3, but you have pandas 3.0.3 which is incompatible.
gluonts 0.16.2 requires numpy<2.2,>=1.16, but you have numpy 2.4.6 which is incompatible.
gluonts 0.16.2 requires pandas<3,>=1.0, but you have pandas 3.0.3 which is incompatible.
hdijupyterutils 0.23.0 requires pandas<3.0.0, but you have pandas 3.0.3 which is incompatible.
jupyter-scheduler 2.12.0 requires psutil~=5.9, but you have psutil 7.2.2 which is incompatible.
jupyter-scheduler 2.12.0 requires pytz<=2024.2,>=2023.3, but you have pytz 2026.2 which is incompatible.
opensearch-py 2.5.0 requires urllib3<2,>=1.26.18, but you have urllib3 2.7.0 which is incompatible.
opentelemetry-instrumentation 0.62b0 requires opentelemetry-semantic-conventions==0.62b0, but you have opentelemetry-semantic-conventions 0.63b1 which is incompatible.
sagemaker-studio 1.1.14 requires numpy<2.3.0,>=1.26.4, but you have numpy 2.4.6 which is incompatible.
sagemaker-studio 1.1.14 requires pandas<3.0.0,>=2.3.2, but you have pandas 3.0.3 which is incompatible.
sagemaker-studio-analytics-extension 0.3.0 requires sparkmagic==0.22.0, but you have sparkmagic 0.21.0 which is incompatible.
snowflake-connector-python 3.17.4 requires cffi<2.0.0,>=1.9, but you have cffi 2.0.0 which is incompatible.
sparkmagic 0.21.0 requires pandas<2.0.0,>=0.17.1, but you have pandas 3.0.3 which is incompatible.
strands-agents-tools 0.1.9 requires pillow<12.0.0,>=11.2.1, but you have pillow 12.2.0 which is incompatible.
sagemaker-train 1.12.0 requires sagemaker-core>=2.12.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-serve 1.12.0 requires sagemaker-core>=2.12.0, but you have sagemaker-core 1.0.78 which is incompatible.
sagemaker-mlops 1.12.0 requires sagemaker-core>=2.12.0, but you have sagemaker-core 1.0.78 which is incompatible.
mlflow-skinny 3.12.0 requires starlette<1, but you have starlette 1.1.0 which is incompatible.
mlflow 3.12.0 requires pandas<3, but you have pandas 3.0.3 which is incompatible.

Successfully installed annotated-doc-0.0.4 annotated-types-0.7.0 antlr4-python3-runtime-4.9.3 anyio-4.13.0 attrs-25.4.0 boto3-1.43.14 botocore-1.43.14 certifi-2026.5.20 charset_normalizer-3.4.7 click-8.4.1 cloudpickle-3.1.2 dill-0.4.1 docker-7.1.0 fastapi-0.136.3 google-pasta-0.2.0 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 h11-0.16.0 idna-3.16 importlib-metadata-6.11.0 jmespath-1.1.0 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 markdown-it-py-4.2.0 mdurl-0.1.2 mock-4.0.3 multiprocess-0.70.19 numpy-2.4.6 omegaconf-2.3.0 packaging-24.2 pandas-3.0.3 pathos-0.3.5 platformdirs-4.9.6 pox-0.3.7 ppft-1.7.8 protobuf-6.33.6 psutil-7.2.2 pydantic-2.13.4 pydantic-core-2.46.4 pygments-2.20.0 python-dateutil-2.9.0.post0 pyyaml-6.0.3 referencing-0.37.0 requests-2.34.2 rich-14.3.4 rpds-py-0.30.0 s3transfer-0.17.0 sagemaker-2.257.3 sagemaker-core-1.0.78 schema-0.7.8 six-1.17.0 smdebug-rulesconfig-1.0.1 starlette-1.1.0 tblib-3.2.2 tqdm-4.67.3 typing-extensions-4.15.0 typing-inspection-0.4.2 urllib3-2.7.0 uvicorn-0.48.0 zipp-4.1.0

Note: you may need to restart the kernel to use updated packages.

In [2]:
import boto3
import sagemaker
from sagemaker.session import Session
from sagemaker import get_execution_role
import pandas as pd
import numpy as np
import time
from time import gmtime, strftime, sleep
from sagemaker.feature_store.feature_group import FeatureGroup
import pprint

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml

sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml

In [3]:
print("sagemaker version:", sagemaker.__version__)  # expect something like 2.254.x

sagemaker version: 2.257.3

In [4]:
original_boto3_version = boto3.__version__
#%pip install -q 'boto3>1.17.21'

In [5]:
region = boto3.Session().region_name
boto_session = boto3.Session(region_name=region)

sagemaker_client     = boto_session.client("sagemaker", region_name=region)
featurestore_runtime = boto_session.client("sagemaker-featurestore-runtime", region_name=region)

feature_store_session = Session(
    boto_session=boto_session,
    sagemaker_client=sagemaker_client,
    sagemaker_featurestore_runtime_client=featurestore_runtime,
)

default_s3_bucket_name = feature_store_session.default_bucket()
prefix = "sagemaker-featurestore-homework-3-1"
print("Region :", region)
print("Bucket :", default_s3_bucket_name)

Region : us-east-1
Bucket : sagemaker-us-east-1-697214847177

In [6]:
role = get_execution_role()
print("Role   :", role)

Role   : arn:aws:iam::697214847177:role/LabRole

In [7]:
HOUSING_PATH = "housing.csv"
GMAPS_PATH   = "housing_gmaps_data_raw.csv"

housing = pd.read_csv(HOUSING_PATH)
gmaps   = pd.read_csv(GMAPS_PATH)

print("housing:", housing.shape, "  gmaps:", gmaps.shape)
housing.head()

housing: (20640, 10)   gmaps: (12590, 30)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [8]:
gmaps_slim = (gmaps[["latitude", "longitude", "neighborhood-political", "postal_code"]]
              .drop_duplicates(subset=["latitude", "longitude"]))

df = housing.merge(gmaps_slim, on=["latitude", "longitude"], how="left")

# neighborhood label
df = df[df["neighborhood-political"].notna()].copy()

print("Rows after join + neighborhood filter:", len(df))
print("Distinct neighborhoods               :", df['neighborhood-political'].nunique())

Rows after join + neighborhood filter: 9000
Distinct neighborhoods               : 1306

In [9]:
# one-hot encode ocean_proximity with all 5 categories enforced
ALL_OCEAN = ["<1H OCEAN", "INLAND", "ISLAND", "NEAR BAY", "NEAR OCEAN"]
df["ocean_proximity"] = pd.Categorical(df["ocean_proximity"], categories=ALL_OCEAN)

ocean_oh = pd.get_dummies(df["ocean_proximity"]).astype(int)
ocean_oh.columns = (ocean_oh.columns.str.lower()
                                    .str.replace("<1h ocean", "lt_1h_ocean", regex=False)
                                    .str.replace(" ", "_"))
df = pd.concat([df, ocean_oh], axis=1)

OH_COLS = list(ocean_oh.columns)
print("One-hot columns:", OH_COLS)

One-hot columns: ['lt_1h_ocean', 'inland', 'island', 'near_bay', 'near_ocean']

In [10]:
# bedrooms_per_household at the row level
df["bedrooms_per_household"] = df["total_bedrooms"] / df["households"]

# Impute: where the ratio is NaN (because total_bedrooms was null),
# fill with the mean ratio for that row's postal code
df["bedrooms_per_household"] = (df.groupby("postal_code")["bedrooms_per_household"]
                                  .transform(lambda s: s.fillna(s.mean())))

# Safety net: a postal code with zero non-null ratios would leave residual NaNs
df["bedrooms_per_household"] = df["bedrooms_per_household"].fillna(
    df["bedrooms_per_household"].mean()
)

print("Residual nulls in bedrooms_per_household:", df["bedrooms_per_household"].isna().sum())

Residual nulls in bedrooms_per_household: 0

In [11]:
agg = (df.groupby("neighborhood-political")
         .agg(**{c: (c, "max") for c in OH_COLS},
              median_house_value   = ("median_house_value", "mean"),
              median_house_age_raw = ("housing_median_age", "mean"),
              total_households     = ("households",         "mean"),
              bedrooms_per_household = ("bedrooms_per_household", "mean"))
         .reset_index()
         .rename(columns={"neighborhood-political": "neighborhood"}))

# Cap median_house_value at 500,000
agg["median_house_value"] = agg["median_house_value"].clip(upper=500000)

# Round households up to integer
agg["total_households"] = np.ceil(agg["total_households"]).astype(int)

# Bucket the averaged median house age into 10year ranges
def age_bucket(avg_age):
    lo = int(avg_age // 10) * 10
    return f"{lo}-{lo+9}"

agg["median_house_age"] = agg["median_house_age_raw"].apply(age_bucket)
agg = agg.drop(columns=["median_house_age_raw"])

# Final column order
neighborhood_features = agg[
    ["neighborhood"] + OH_COLS +
    ["median_house_value", "median_house_age", "total_households", "bedrooms_per_household"]
].copy()

print("Feature group shape:", neighborhood_features.shape)
print("Any nulls?", neighborhood_features.isna().any().any())
neighborhood_features.head()

Feature group shape: (1306, 10)
Any nulls? False

,neighborhood,lt_1h_ocean,inland,island,near_bay,near_ocean,median_house_value,median_house_age,total_households,bedrooms_per_household
0,28 Palms,1,0,0,0,0,222200.000000,20-29,923,1.017335
1,Acorn Industrial,0,0,0,1,0,81300.000000,50-59,147,1.659864
2,Adams Hill,1,0,0,0,0,250733.333333,30-39,494,1.034649
3,Agua Mansa Industrial Corridor,0,1,0,0,0,112300.000000,10-19,516,1.102713
4,Al Tahoe,0,1,0,0,0,109180.000000,20-29,249,1.641739

In [12]:
#Building the Feature Group

In [13]:
def cast_object_to_string(frame):
    for col in frame.columns:
        if frame.dtypes[col] == "object":
            frame[col] = frame[col].astype("str").astype("string")

cast_object_to_string(neighborhood_features)

record_identifier_feature_name = "neighborhood"
event_time_feature_name        = "event_time"

current_time_sec = float(round(time.time()))
neighborhood_features[event_time_feature_name] = pd.Series(
    [current_time_sec] * len(neighborhood_features), dtype="float64"
)

neighborhood_features.dtypes

neighborhood                  str
lt_1h_ocean                 int64
inland                      int64
island                      int64
near_bay                    int64
near_ocean                  int64
median_house_value        float64
median_house_age              str
total_households            int64
bedrooms_per_household    float64
event_time                float64
dtype: object

In [16]:
for col in ["neighborhood", "median_house_age"]:
    neighborhood_features[col] = neighborhood_features[col].astype(object)

print(neighborhood_features.dtypes)  # verify

neighborhood               object
lt_1h_ocean                 int64
inland                      int64
island                      int64
near_bay                    int64
near_ocean                  int64
median_house_value        float64
median_house_age           object
total_households            int64
bedrooms_per_household    float64
event_time                float64
dtype: object

In [17]:
neighborhood_feature_group_name = "neighborhood-feature-group-" + strftime("%d-%H-%M-%S", gmtime())
print("FeatureGroup name:", neighborhood_feature_group_name)

neighborhood_feature_group = FeatureGroup(
    name=neighborhood_feature_group_name,
    sagemaker_session=feature_store_session,
)

neighborhood_feature_group.load_feature_definitions(data_frame=neighborhood_features)

FeatureGroup name: neighborhood-feature-group-25-14-30-23

[FeatureDefinition(feature_name='neighborhood', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None),
 FeatureDefinition(feature_name='lt_1h_ocean', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='inland', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='island', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='near_bay', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='near_ocean', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='median_house_value', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='median_house_age', feature_type=<FeatureTypeEnum.STRING: 'String'>, collection_type=None),
 FeatureDefinition(feature_name='total_households', feature_type=<FeatureTypeEnum.INTEGRAL: 'Integral'>, collection_type=None),
 FeatureDefinition(feature_name='bedrooms_per_household', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None),
 FeatureDefinition(feature_name='event_time', feature_type=<FeatureTypeEnum.FRACTIONAL: 'Fractional'>, collection_type=None)]

In [18]:
def wait_for_feature_group_creation_complete(fg):
    status = fg.describe().get("FeatureGroupStatus")
    while status == "Creating":
        print("Waiting for FeatureGroup creation...")
        time.sleep(5)
        status = fg.describe().get("FeatureGroupStatus")
    if status != "Created":
        raise RuntimeError(f"Failed to create FeatureGroup {fg.name}")
    print(f"FeatureGroup {fg.name} successfully created.")

neighborhood_feature_group.create(
    s3_uri=f"s3://{default_s3_bucket_name}/{prefix}",
    record_identifier_name=record_identifier_feature_name,
    event_time_feature_name=event_time_feature_name,
    role_arn=role,
    enable_online_store=True,
)

wait_for_feature_group_creation_complete(neighborhood_feature_group)

Waiting for FeatureGroup creation...

Waiting for FeatureGroup creation...

Waiting for FeatureGroup creation...

Waiting for FeatureGroup creation...

FeatureGroup neighborhood-feature-group-25-14-30-23 successfully created.

In [19]:
neighborhood_feature_group.describe()

{'FeatureGroupArn': 'arn:aws:sagemaker:us-east-1:697214847177:feature-group/neighborhood-feature-group-25-14-30-23',
 'FeatureGroupName': 'neighborhood-feature-group-25-14-30-23',
 'RecordIdentifierFeatureName': 'neighborhood',
 'EventTimeFeatureName': 'event_time',
 'FeatureDefinitions': [{'FeatureName': 'neighborhood',
   'FeatureType': 'String'},
  {'FeatureName': 'lt_1h_ocean', 'FeatureType': 'Integral'},
  {'FeatureName': 'inland', 'FeatureType': 'Integral'},
  {'FeatureName': 'island', 'FeatureType': 'Integral'},
  {'FeatureName': 'near_bay', 'FeatureType': 'Integral'},
  {'FeatureName': 'near_ocean', 'FeatureType': 'Integral'},
  {'FeatureName': 'median_house_value', 'FeatureType': 'Fractional'},
  {'FeatureName': 'median_house_age', 'FeatureType': 'String'},
  {'FeatureName': 'total_households', 'FeatureType': 'Integral'},
  {'FeatureName': 'bedrooms_per_household', 'FeatureType': 'Fractional'},
  {'FeatureName': 'event_time', 'FeatureType': 'Fractional'}],
 'CreationTime': datetime.datetime(2026, 5, 25, 14, 30, 27, 789000, tzinfo=tzlocal()),
 'OnlineStoreConfig': {'EnableOnlineStore': True},
 'OfflineStoreConfig': {'S3StorageConfig': {'S3Uri': 's3://sagemaker-us-east-1-697214847177/sagemaker-featurestore-homework-3-1',
   'ResolvedOutputS3Uri': 's3://sagemaker-us-east-1-697214847177/sagemaker-featurestore-homework-3-1/697214847177/sagemaker/us-east-1/offline-store/neighborhood-feature-group-25-14-30-23-1779719427/data'},
  'DisableGlueTableCreation': False,
  'DataCatalogConfig': {'TableName': 'neighborhood_feature_group_25_14_30_23_1779719427',
   'Catalog': 'AwsDataCatalog',
   'Database': 'sagemaker_featurestore'}},
 'ThroughputConfig': {'ThroughputMode': 'OnDemand'},
 'RoleArn': 'arn:aws:iam::697214847177:role/LabRole',
 'FeatureGroupStatus': 'Created',
 'OnlineStoreTotalSizeBytes': 0,
 'ResponseMetadata': {'RequestId': 'f902bd14-5442-4579-bf02-7f604324dcc8',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'f902bd14-5442-4579-bf02-7f604324dcc8',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '2136',
   'date': 'Mon, 25 May 2026 14:31:48 GMT'},
  'RetryAttempts': 0}}

In [20]:
neighborhood_feature_group.ingest(
    data_frame=neighborhood_features,
    max_workers=3,
    wait=True,
)

IngestionManagerPandas(feature_group_name='neighborhood-feature-group-25-14-30-23', feature_definitions={'neighborhood': {'FeatureName': 'neighborhood', 'FeatureType': 'String'}, 'lt_1h_ocean': {'FeatureName': 'lt_1h_ocean', 'FeatureType': 'Integral'}, 'inland': {'FeatureName': 'inland', 'FeatureType': 'Integral'}, 'island': {'FeatureName': 'island', 'FeatureType': 'Integral'}, 'near_bay': {'FeatureName': 'near_bay', 'FeatureType': 'Integral'}, 'near_ocean': {'FeatureName': 'near_ocean', 'FeatureType': 'Integral'}, 'median_house_value': {'FeatureName': 'median_house_value', 'FeatureType': 'Fractional'}, 'median_house_age': {'FeatureName': 'median_house_age', 'FeatureType': 'String'}, 'total_households': {'FeatureName': 'total_households', 'FeatureType': 'Integral'}, 'bedrooms_per_household': {'FeatureName': 'bedrooms_per_household', 'FeatureType': 'Fractional'}, 'event_time': {'FeatureName': 'event_time', 'FeatureType': 'Fractional'}}, sagemaker_fs_runtime_client_config=<botocore.config.Config object at 0x7f7b7bdf73e0>, sagemaker_session=<sagemaker.session.Session object at 0x7f7b7cea0110>, max_workers=3, max_processes=1, profile_name=None, _async_result=<multiprocess.pool.MapResult object at 0x7f7b79656420>, _processing_pool=<pool ProcessPool(ncpus=1)>, _failed_indices=[])

In [21]:
def fetch(neighborhood_name):
    resp = featurestore_runtime.get_record(
        FeatureGroupName=neighborhood_feature_group_name,
        RecordIdentifierValueAsString=neighborhood_name,
    )
    print(f"=== {neighborhood_name} ===")
    pprint.pp(resp["Record"])
    print()
    return resp

_ = fetch("Brooktree")

=== Brooktree ===
[{'FeatureName': 'neighborhood', 'ValueAsString': 'Brooktree'},
 {'FeatureName': 'lt_1h_ocean', 'ValueAsString': '1'},
 {'FeatureName': 'inland', 'ValueAsString': '0'},
 {'FeatureName': 'island', 'ValueAsString': '0'},
 {'FeatureName': 'near_bay', 'ValueAsString': '0'},
 {'FeatureName': 'near_ocean', 'ValueAsString': '0'},
 {'FeatureName': 'median_house_value', 'ValueAsString': '257400.0'},
 {'FeatureName': 'median_house_age', 'ValueAsString': '0-9'},
 {'FeatureName': 'total_households', 'ValueAsString': '1438'},
 {'FeatureName': 'bedrooms_per_household',
  'ValueAsString': '1.0747777761942723'},
 {'FeatureName': 'event_time', 'ValueAsString': '1779718688.0'}]

In [22]:
_ = fetch("Fisherman's Wharf")

=== Fisherman's Wharf ===
[{'FeatureName': 'neighborhood', 'ValueAsString': "Fisherman's Wharf"},
 {'FeatureName': 'lt_1h_ocean', 'ValueAsString': '0'},
 {'FeatureName': 'inland', 'ValueAsString': '0'},
 {'FeatureName': 'island', 'ValueAsString': '0'},
 {'FeatureName': 'near_bay', 'ValueAsString': '1'},
 {'FeatureName': 'near_ocean', 'ValueAsString': '0'},
 {'FeatureName': 'median_house_value', 'ValueAsString': '500000.0'},
 {'FeatureName': 'median_house_age', 'ValueAsString': '50-59'},
 {'FeatureName': 'total_households', 'ValueAsString': '250'},
 {'FeatureName': 'bedrooms_per_household', 'ValueAsString': '1.268'},
 {'FeatureName': 'event_time', 'ValueAsString': '1779718688.0'}]

In [23]:
_ = fetch("Los Osos")

=== Los Osos ===
[{'FeatureName': 'neighborhood', 'ValueAsString': 'Los Osos'},
 {'FeatureName': 'lt_1h_ocean', 'ValueAsString': '0'},
 {'FeatureName': 'inland', 'ValueAsString': '0'},
 {'FeatureName': 'island', 'ValueAsString': '0'},
 {'FeatureName': 'near_bay', 'ValueAsString': '0'},
 {'FeatureName': 'near_ocean', 'ValueAsString': '1'},
 {'FeatureName': 'median_house_value', 'ValueAsString': '221612.5'},
 {'FeatureName': 'median_house_age', 'ValueAsString': '10-19'},
 {'FeatureName': 'total_households', 'ValueAsString': '612'},
 {'FeatureName': 'bedrooms_per_household',
  'ValueAsString': '1.0478845404823531'},
 {'FeatureName': 'event_time', 'ValueAsString': '1779718688.0'}]

In [24]:
batch = featurestore_runtime.batch_get_record(Identifiers=[{
    "FeatureGroupName": neighborhood_feature_group_name,
    "RecordIdentifiersValueAsString": ["Brooktree", "Fisherman's Wharf", "Los Osos"],
}])

rows = []
for rec in batch["Records"]:
    rows.append({f["FeatureName"]: f["ValueAsString"] for f in rec["Record"]})

pd.DataFrame(rows).set_index("neighborhood")

,lt_1h_ocean,inland,island,near_bay,near_ocean,median_house_value,median_house_age,total_households,bedrooms_per_household,event_time
neighborhood,,,,,,,,,,
Brooktree,1,0,0,0,0,257400.0,0-9,1438,1.0747777761942723,1779718688.0
Fisherman's Wharf,0,0,0,1,0,500000.0,50-59,250,1.268,1779718688.0
Los Osos,0,0,0,0,1,221612.5,10-19,612,1.0478845404823531,1779718688.0